sudo: required
dist: trusty
language: cpp

compiler:
 - gcc

before_install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-trusty
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qy update

install:
 - sudo apt-get -qy install qt510base qt510tools
 - sudo apt-get -qy install gcc-5 g++-5
 - sudo apt-get -qy install libsystemd-daemon-dev
 - sudo apt-get -qy install lcov python
 - wget https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh && sudo sh cmake-3.10.3-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir

script:
 - export CXX=g++-5
 - export CC=gcc-5
 - /usr/local/bin/cmake -DCMAKE_PREFIX_PATH=/opt/qt510/lib/cmake -DCMAKE_BUILD_TYPE=Debug .
 - make VERBOSE=1
 - make coverage

after_success:
 - bash <(curl -s https://codecov.io/bash)

os:
 - linux
