sudo: required
dist: bionic
language: cpp

compiler:
 - gcc

before_install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.3-bionic
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:jonathonf/python-3.6
 - sudo apt-get -qy update

install:
 - sudo apt-get -qy install qt511base qt511tools
 - sudo apt-get -qy install gcc-5 g++-5
 - sudo apt-get -qy install libsystemd-daemon-dev lcov python3.6 dbus-test-runner
 - wget https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh && sudo sh cmake-3.10.3-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir

script:
 - export CXX=g++-5
 - export CC=gcc-5
 - /usr/local/bin/cmake -DCMAKE_PREFIX_PATH=/opt/qt511/lib/cmake -DCMAKE_BUILD_TYPE=Debug .
 - make VERBOSE=1
 - make coverage

after_success:
 - bash <(curl -s https://codecov.io/bash)

os:
 - linux
